### ISSUE TITLE
Can't run the simulator

### ISSUE THREAD

**Issue by tianyatomy** [Apophenic/OBD_Simulator#1]
Hello, I tried to run the simulator by "python Program.py -address=localhost -port=1090 -shell", but I got an error. Do I need to config anything else?

a212437822@212437822s-MacBook-Air.local:/Users/a212437822/git/ELM327-OBD-Simulator/src> python Program.py -address=localhost -port=1090 -shell                      16-04-07 10:32
Traceback (most recent call last):
  File "Program.py", line 30, in <module>
    import Server
  File "/Users/a212437822/git/ELM327-OBD-Simulator/src/Server.py", line 1, in <module>
    import IO
  File "/Users/a212437822/git/ELM327-OBD-Simulator/src/IO.py", line 1, in <module>
    from Mode01.Response.Other.AuxInputStatus import AuxInputStatus
ImportError: No module named Mode01.Response.Other.AuxInputStatus

**Comment by mahmudsamiunlu** [comment]
Same happend to me and i seach a lot and find. 
Add __init__.py all folder and it fixed.

**Comment by phancongphuoc** [comment]
After running the Program.py, how can I get ELM data? I cannot found any document
